[workspace]
members = ["api", "kernel", "modules/*"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
los-api = { path = "api" }

[profile.dev]
opt-level = 1

[profile.dev.package.embedded-term]
opt-level = 3
