# Timeout in seconds that Limine will use before automatically booting.
timeout: 3
serial: yes
verbose: yes

# The entry name that will be displayed in the boot menu.
/OS For Fun
    # We use the Limine boot protocol.
    protocol: limine
    kaslr: no

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    kernel_path: boot():/boot/kernel
