[unstable]
build-std = [
    "alloc",
    "core",
    "compiler_builtins"
]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-pc-los-kernel"

[env]
RUST_TARGET_PATH = { value = "targets", relative = true }
