use core::arch::global_asm;

global_asm! {
    ".global _start",
    ".type _start, STT_FUNC",
    ".size _start, _start._end-_start",
    "_start:",
    "pop rdi",
    "lea rsi, [rsp]",
    "test eax, 1",
    "je 3f",
    "mov rdx, r12",
    "mov rcx, rbx",
    "jmp {entry}",
    "3:",
    "mov rdx, rsi",
    "2:",
    "mov rax, [rdx]",
    "lea rdx, [rdx+8]",
    "test rax, rax",
    "jnz 2b",
    "mov rcx, rdx",
    "2:",
    "mov rax, [rcx]",
    "lea rcx, [rcx+8]",
    "test rax, rax",
    "jnz 2b",
    "jmp {entry}",
    "_start._end:",
    entry = sym super::begin_kernel,
}
